http:
  middlewares:
    simpleAuth:
      basicAuth:
        users:
          - 'admin:<secret>'
  routers:
    api:
      rule: Host(`<your domain>`)
      entrypoints:
        - websecure
      middlewares:
        - simpleAuth
      service: api@internal
      tls:
        certResolver: lets-encrypt
