entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'

api:
  dashboard: true

certificatesResolvers:
  lets-encrypt:
    acme:
      email: <your email address>
      storage: /letsencrypt/acme.json
      tlsChallenge: {}

providers:
  docker:
    watch: true
    network: web
    exposedByDefault: false
  file:
    filename: traefik_api.yml
